[book]
authors = ["miguehm"]
language = "en"
multilingual = false
src = "src"
title = "base-datos"

[output.html.fold]
enable = true
level = 1

[output.html]
mathjax-support = true

[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
